Prepare new version of the charter
w3c/web-networks-charter pull request #25
Opened 2020-11-03 14:42 UTC by dontcallmedom

2020-11-04 04:21 UTC, sudeepdi reviewed
+1 Looks good to me

2020-11-04 04:33 UTC, sudeepdi requested changes
Apart from one minor typo correction required (see comment inserted in doc), rest of the first draft looks good.

2020-11-04 04:33 UTC, sudeepdi commented on index.html
> +              in the cloud when exposing interactions between Things, which can also include Edeg devices. The Web &
Spelling error "Edeg". Change to "Edge"

2020-11-05 16:54 UTC, anssiko approved these changes

2020-11-06 02:36 UTC, sudeepdi approved these changes
+1

2020-11-09 07:31 UTC, merged